# Version 1.0.0
# Created by CJ Burkey

# Shop name
Inv Name: '&2Shoppe'

# Sell percent
# 50% = 0.5
# 5% = 0.05
Sell Per: 0.25

# Tabs
# id,name,icon:data
tabs:
  - 0,&2Building Blocks,BRICK:0
  - 1,&2Decorations Blocks,DOUBLE_PLANT:5
  - 2,&2Redstone,REDSTONE:0
  - 3,&2Transportation,POWERED_RAIL:0
  - 4,&2Miscellaneous,LAVA_BUCKET:0
  - 5,&2Foodstuffs,APPLE:0
  - 6,&2Tools,IRON_AXE:0
  - 7,&2Combat,GOLD_SWORD:0
  - 8,&2Materials,STICK:0

# Items
# tabid,item/block:data,buy
items:
  # Building Blocks
  - 0,STONE:0,75
  - 0,STONE:1,75
  - 0,STONE:2,75
  - 0,STONE:3,75
  - 0,STONE:4,75
  - 0,STONE:5,75
  - 0,STONE:6,75
  - 0,GRASS:0,50
  - 0,DIRT:0,20
  - 0,DIRT:1,20
  - 0,DIRT:2,20
  - 0,COBBLESTONE:0,75
  - 0,WOOD:0,25
  - 0,WOOD:1,25
  - 0,WOOD:2,25
  - 0,WOOD:3,25
  - 0,WOOD:4,25
  - 0,WOOD:5,25
  - 0,SAND:0,30
  - 0,SAND:1,30
  - 0,GRAVEL:0,20
  - 0,GOLD_ORE:0,500
  - 0,IRON_ORE:0,250
  - 0,COAL_ORE:0,75
  - 0,LOG:0,100
  - 0,LOG:1,100
  - 0,LOG:2,100
  - 0,LOG:3,100
  - 0,SPONGE:0,400
  - 0,GLASS:0,50
  - 0,LAPIS_ORE:0,150
  - 0,SANDSTONE:0,40
  - 0,SANDSTONE:1,40
  - 0,SANDSTONE:2,40
  - 0,WOOL:0,50
  - 0,GOLD_BLOCK:0,3000
  - 0,IRON_BLOCK:0,1500
  - 0,STEP:0,5
  - 0,STEP:1,5
  - 0,STEP:3,5
  - 0,STEP:4,5
  - 0,STEP:5,5
  - 0,STEP:6,5
  - 0,STEP:7,5
  - 0,BRICK:0,100
  - 0,BOOKSHELF:0,300
  - 0,OBSIDIAN:0,3000
  - 0,WOOD_STAIRS:0,5
  - 0,DIAMOND_ORE:0,0
  - 0,COBBLESTONE_STAIRS:0,0
  - 0,REDSTONE_ORE:0,0
  - 0,ICE:0,0
  - 0,SNOW:0,0
  - 0,CLAY:0,0
  - 0,PUMPKIN:0,0
  - 0,NETHERRACK:0,0
  - 0,SOUL_SAND:0,0
  - 0,GLOWSTONE:0,0
  - 0,SMOOTH_BRICK:0,0
  - 0,MELON_BLOCK:0,0
  - 0,BRICK_STAIRS:0,0
  - 0,SMOOTH_STAIRS:0,0
  - 0,MYCEL:0,0
  - 0,NETHER_BRICK:0,0
  - 0,NETHER_BRICK_STAIRS:0,0
  - 0,ENDER_STONE:0,0
  - 0,WOOD_STEP:1,0
  - 0,WOOD_STEP:2,0
  - 0,WOOD_STEP:3,0
  - 0,WOOD_STEP:4,0
  - 0,WOOD_STEP:5,0
  - 0,WOOD_STEP:6,0
  - 0,SANDSTONE_STAIRS:0,0
  - 0,EMERALD_ORE:0,0
  - 0,EMERALD_BLOCK:0,0
  - 0,SPRUCE_WOOD_STAIRS:0,0
  - 0,BIRCH_WOOD_STAIRS:0,0
  - 0,JUNGLE_WOOD_STAIRS:0,0
  - 0,COBBLE_WALL:0,0
  - 0,QUARTZ_ORE:0,0
  - 0,QUARTZ_BLOCK:0,0
  - 0,QUARTZ_STAIRS:0,0
  - 0,LOG_2:0,0
  - 0,LOG_2:1,0
  - 0,ACACIA_STAIRS:0,0
  - 0,DARK_OAK_STAIRS:0,0
  - 0,PRISMARINE:0,0
  - 0,PRISMARINE:1,0
  - 0,PRISMARINE:2,0
  - 0,SEA_LANTERN:0,0
  - 0,HAY_BLOCK:0,0
  - 0,HARD_CLAY:0,0
  - 0,COAL_BLOCK:0,0
  - 0,PACKED_ICE:0,0
  - 0,RED_SANDSTONE:0,0
  - 0,RED_SANDSTONE_STAIRS:0,0
  # Decoration Blocks
  - 1,SAPLING:0,0